package com.modulus.qbar.core.primitive;

import com.modulus.qbar.core.QBObject;
import com.modulus.qbar.core.QBStruct;

/**
 * Class that represents the
 * Q-Bar primitive value double
 */
 /*
  * this class was generated by the python script
  * 'generate_primitives.py
  * @PythonGenerated
  */
public class QBDouble extends QBPrimitive{
    /**
	 * 
	 */
	private static final long serialVersionUID = -2590117898914328610L;
	private double value;
    
    public final static QBStruct struct = new QBStruct("Double", QBPrimitive.struct) {
		
		/**
		 * 
		 */
		private static final long serialVersionUID = 1L;

		@Override
		public QBObject newInstance() {
			// TODO Auto-generated method stub
			return null;
		}
	};
	
    /**
     * Constructs a new QBarDouble that wraps
     * the type double
     */
    public QBDouble( double value ){
        this.value = value;
    }
    
    @Override
    public int intValue(){
        return (int) this.value;
    }
    
    @Override
    public double doubleValue(){
        return (double) this.value;
    }
    
    @Override
    public char charValue(){
        return (char) this.value;
    }
    
    public String toString(){
    	return Double.toString(value);
    }
    
    public Number getValueNumber(){
    	return value;
    }
    
    @Override
    public Object getWrapped(){
    	return value;
    }
}
